name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' 

    - name: Build Go binary
      run: |
        go build -o postlite -ldflags "-s -w"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: postlite
        path: postlite
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' 

    - name: Build Go binary
      run: |
        go build -o postlite -ldflags "-s -w"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: postlite
        path: postlite